database:
  url: jdbc:mysql://mysql-nzt-dev-rw.bnq.qc:3306/platform_admin
  driver: com.mysql.jdbc.Driver
  username: bnqbt
  password: dev2018@Bnq
  poolSize: 1
generateTable:
  enable: true
  targetDir: ./src/result/
  modelPackage: com.baj.newretail.platform.domain
  queryPackage: com.baj.newretail.platform.query
  mapperPackage: com.baj.newretail.platform.mapper
  examplePackage: com.baj.newretail.platform
  beanJsonPackage: com.baj.newretail.platform.json
  managerPackage: com.baj.newretail.platform.manager
  daoPackage: com.baj.newretail.platform
  xmlPackage: resources.sqlmap
  primaryKey: id
generateController: false