database:
  url: jdbc:mysql://mysql-nzt-dev-rw.bnq.qc:3306/cms_dev
  driver: com.mysql.jdbc.Driver
  username: bnqbt
  password: dev2018@Bnq
  poolSize: 1
generateTable:
  enable: true
  targetDir: ./src/result/
  rootPackage: com.neverbug.fund
  domain: true
  query: true
  manager: true
  dao: true
  mapperXml: true
  primaryKey: id
generateController: false